apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  resources:
    requests:
      storage: 1G
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
